### ISSUE TITLE
Prevent screw head z-axis translation while using the scale option

### ISSUE THREAD

**Issue by luckychris** [hugemenace/nd#76]
if i create a screw head (which works with the update like a charm ;)), i can now choose the screw with my touchpad, but....a little it's a bit annoying that scaling "moves" the screw as well, if i offset it before:

![scaling moves the screw](https://user-images.githubusercontent.com/232549/201513577-9de00518-e957-4e23-a8b7-0afc39ab96d8.gif)

**Comment by tristan-hm** [comment]
Good find. I've always naturally scaled them first, then moved them into position, so I've never noticed this issue before. I'll take a look at fixing it.
