### ISSUE TITLE
adding a panel on multiple faces

### ISSUE THREAD

**Issue by luckychris** [hugemenace/nd#78]
i created a plane, subdivided it a lot and gave it a wave modifier, then i wanted to press F -> panel

<img width="370" alt="image" src="https://user-images.githubusercontent.com/232549/201629446-25c1fad7-120d-4d1b-b1d4-281555f12420.png">

Unfortunately i can now only select single face or shift-select single faces. Is there a way to use at least box select? Or how is it meant to be used?

**Comment by tristan-hm** [comment]
If you have a Discord account, feel free to join our server (https://hugemenace.co/discord) — questions/discussions like this are best suited there.

As with all ND operators, they only pass through certain events where applicable (for example, left-click for selection). It'd be nearly impossible to pass through or handle all Blender shortcut keys/gestures. So in a situation like the one you describe, you could open the panel operator, then **_pause_** the operator (`\` key by default), make your selection (box select, circle select, etc.) and then un-pause the operator and continue.

Here's an example:

https://user-images.githubusercontent.com/77056966/201804599-3a02ae02-db58-47ee-8035-b1e96682560f.mp4
