### ISSUE TITLE
Edge Bevel Error

### ISSUE THREAD

**Issue by Latenight11** [hugemenace/nd#80]
After going to edit mode, select an edge, then press F -- ND Edge Bevel. If I press Esc before confirming the operation I get the following error (see screenshot). The worst is that the addon operator menu stays inactive on the screen obscuring the viewport. I noticed that behavior on the fresh cube. If I am doing the vert bevel first, the edge bevel works fine. 
![Screenshot_1](https://github.com/hugemenace/nd/assets/64140163/0e7ffd42-8818-42b4-9532-a729e0e47469)
![Screenshot_4](https://github.com/hugemenace/nd/assets/64140163/7e88fd62-ff8a-48e8-bd68-e7f396b7ea48)

**Comment by tristan-hm** [comment]
Thanks for reporting the issue. I'll look at fixing it and push out an update in the next few days.

---

As a side note, you can reload the scripts from within Blender whenever an addon encounters an error and leaves the viewport in some undesirable state (like the ND operator menu being stuck open). This avoids having to close and reopen Blender. See the screenshot below:

![Screenshot 2024-01-22 161811](https://github.com/hugemenace/nd/assets/77056966/4ce1b695-204c-4bf9-b4b8-215ce6ecdaf5)

**Comment by tristan-hm** [comment]
This has been fixed in the latest version: **1.39.0**.
