### ISSUE TITLE
Edge Bevel stuck on readjust.

### ISSUE THREAD

**Issue by genesis2303** [hugemenace/nd#84]
When I try to make new edge bevel it just keeps readjusting first one, am I doing sth wrong or this is a bug? (4.1&4.2 Beta on Linux)
Vertex bevel works fine just edge bevel behaves that way.

**Comment by tristan-hm** [comment]
Edge bevels only support one bevel configuration set, as Blender imposes that limitation when using edge weights. This may be updated if Blender adds support for edge groups, similar to vertex groups, in the future.

When you attempt to bevel a new edge using ND's edge bevel, it recalls the general settings for all edges but allows you to interactively change the weight for the new edge by holding CTRL + ALT. 

For a full rundown on bevels, check out the ND Deep Dive series bevel video:

https://www.youtube.com/watch?v=y06Z7xGjYvA
