### ISSUE TITLE
Cycle operator in Modifier mode  - Stop at Current state 

### ISSUE THREAD

**Issue by pixeltrain3D** [hugemenace/nd#99]
When using the Cycle operator in Modifier mode we can see how an object is built step-by-step.
I use it a lot for understanding the modifier stack, because it seems not easy possible to rename the modifiers.

Scenario:
I want to place a new modifier at the correct position in the stack, but I don't know where excactly
So I scroll though the list until I find the correct state of the modifier stack
But when I now click all modifiers are again visible.

I would love a modifier key to drop out of the cycle mode with holding the visibility of the current state. So the position in the modifier stack is now easy to find.

**Comment by tristan-hm** [comment]
Sure, I can add that as an option to the modifier cycle mode - makes sense 👍

**Comment by tristan-hm** [comment]
This will be included in the upcoming ND release.
